### ISSUE TITLE
Overwrite Config.xml

### ISSUE THREAD

**Issue by nheezemans** [tideman/generator-ciberionic#2]
Can you add some additional information why the config.xml needs to be overwritten in the generator messages since it is not clear why this should be done

**Comment by tideman** [comment]
This is still unsolvable. I am not able to force an overwrite. I am also not able to remove the config.xml after generation and to replace it with the templated one because of the error 'This is not a valid cordova project'. I think it is only solvable if there is more restriction to the sequence in with functions are executed.

**Comment by tideman** [comment]
I added instructions about an overwrite to the README
